name: Stock Alert Telegram Bot

on:
  schedule:
    - cron: '0 14 * * 1-5'  # Run at 14:00 UTC Mon-Fri (market hours)
  workflow_dispatch:         # Manual trigger

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run the bot script
      env:
        api_alpha: ${{ secrets.API_ALPHA }}
        api_news: ${{ secrets.API_NEWS }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python main.py
